version: '3.8'

services:
  book-service:
    image: ${DOCKER_REGISTRY-}bookservice
    build:
      context: .
      dockerfile: Services/Book/Book.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONEMENT=Development
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - rabbitmq
      - identity-service
    restart: unless-stopped
    
  
  search-service:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: Services/Search/Search.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONEMENT=Development
      - ASPNETCORE_HTTPS_PORT=6001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 6000:80
      - 6001:443
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - elasticsearch  
      - identity-service
      - rabbitmq

  identity-service:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONEMENT=Development
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - ~/.aspnet/https:/https:ro
        
  stock-delivery-service:
    image: ${DOCKER_REGISTRY-}stockdeliveryservice
    build:
      context: .
      dockerfile: Services/StockDelivery/StockDelivery.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONEMENT=Development
      - ASPNETCORE_HTTPS_PORT=7001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 7000:80
      - 7001:443
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - rabbitmq
    restart: unless-stopped


  user-service:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: Services/User/User/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONEMENT=Development
      - ASPNETCORE_HTTPS_PORT=10001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 10000:80
      - 10001:443
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - rabbitmq
      - search-service
    restart: unless-stopped
    
  lend-service:
    image: ${DOCKER_REGISTRY-}lendservice
    build:
      context: .
      dockerfile: Services/Lend/Lend.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONEMENT=Development
      - ASPNETCORE_HTTPS_PORT=11001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 11000:80
      - 11001:443
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - rabbitmq
    restart: unless-stopped
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
#    Uncomment for persist data after destroying elasticsearch container
#    volumes:
#      -  esdata:/usr/share/elasticsearch/data        
#volumes:
#  esdata:
#    driver: local

  rabbitmq:
    image: rabbitmq:3.8.16-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672